### ISSUE TITLE
mouse manipulations example not working in Chrome

### ISSUE THREAD

**Issue by dhatcher** [jacomyal/sigma.js#1229] opened 2022-04-05 19:52 UTC
**Web browser:** Chrome 100.0.4896.60

### Steps to reproduce

On the sample here: https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/mouse-manipulations 

### Expected behavior

Should be able to drag nodes

### Actual behavior

Nodes shake a bit but don't actually move relative to the entire graph. 

## Note

I tested in Edge and the behavior seemed correct.

**Comment by Yomguithereal** [comment] 2022-04-05 20:00
Hello @dhatcher, I cannot reproduce your issue on a chrome v100 on mac on my end, nor in any browser I have. Can you tell us if you see an error in the console? Else can you post some kind of gif demonstrating the issue?

**Comment by dhatcher** [comment] 2022-04-05 20:05
![move_node](https://user-images.githubusercontent.com/4562725/161839950-8c21ea26-7382-46cd-8705-9af9eb0fb29e.gif)


I'm running on Windows if that makes a difference.

**Comment by jacomyal** [comment] 2022-04-06 07:11
I think I know what's happening: In the last two days, I released [a commit](https://github.com/jacomyal/sigma.js/commit/b7e45548d3dfdbfb8237a935db13b1c3baf88b6c) changing the way this example behaves, and a new version of sigma.

Your GIF shows the latest version of the example, running on sigma v2.2.0. Indeed, the camera is no more disabled but the `e.preventSigmaDefault();` is not working yet. So when you move the mouse, the graph moves as well.

It should be fixed soon, at least as soon as your cache or CodeSandbox's cache switches to sigma v2.3.0.

**Closed by jacomyal** 2022-04-06 07:11 UTC
Labels: bug

**Comment by dhatcher** [comment] 2022-04-06 13:33
Yes that looks like the issue.
