### ISSUE TITLE
ForceAtlas on a subset

### ISSUE THREAD

**Issue by CGenie** [jacomyal/sigma.js#1291] opened 2022-10-19 16:00 UTC
Hello,

This is related to https://github.com/jacomyal/sigma.js/issues/15 but since sigma.js was rewritten I guess I can reopen that issue.

Thing is, it would be very useful if forceatlas was able to run on hidden nodes.

What I currently do is: keep the original graph state in some variable, when user starts forceatlas, I first `dropNode`/`dropEdge` for hidden node/edge ids and then I call `fa2.start()`. When user stops forceatlas, I bring back the graph from my variable (I have a diffing function which can `addNode` only for missing nodes, same for edges).

I guess the ideal situation here would be that forceAtlas could operate on a subgraph of the original `sigma.graph`. Some code is in place, i.e. `FA2Layout` accepts a graph as a parameter, which in fact doesn't have to be the same as `sigma.graph`, so decoupling is here already. However with this approach we would need some way to "couple" the two graphs so that forceatlas changes are rendered properly.

**Comment by Yomguithereal** [comment] 2022-10-20 08:19
Hello @CGenie, I will transfer this issue to `graphology` because it does not really concern sigma.js.

What you need is on the roadmap. We need to "modernize" the FA2 code a little bit to be able to better tweak which nodes are hidden, so excluded from the layout and which nodes are fixed but still affect the layout. It will be done with getter functions like for `graphology-layout-force` here: https://graphology.github.io/standard-library/layout-force but we need some time.

**Comment by Yomguithereal** [comment] 2022-10-20 08:22
I actually cannot transfer the issue to graphology, so I will mark your issue as a duplicate of graphology/graphology#324 and close it here.

**Closed by Yomguithereal** 2022-10-20 08:22 UTC
Labels: enhancement

**Comment by CGenie** [comment] 2022-10-20 08:24
Ok, thanks!
