### ISSUE TITLE
on v2 nodes labels disappear randomly on zooming

### ISSUE THREAD

**Issue by knowledgeplaces** [jacomyal/sigma.js#1128] opened 2021-07-11 09:17 UTC
I have been able to display a simple graph in my angular 12 app, but as soon as I zoom in or out, using the mouse wheel for instance, some nodes labels disappear. May be same bug as https://github.com/jacomyal/sigma.js/issues/1125.

**Comment by sim51** [comment] 2021-07-11 09:58
To help us understand your issue, please specify important details, primarily:

- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) console logs, stacktraces, and other debug info.

FYI: Node's label are displayed depending of their size, and this can be configure with the setting `labelGrid.renderedSizeThreshold`  (https://github.com/jacomyal/sigma.js/blob/df3e5fd3e30dff30045be9ee8a427ae710647706/src/settings.ts#L57)

**Comment by knowledgeplaces** [comment] 2021-07-11 10:32
Here is my code:
`		////////////// SIGMA TEST HERE /////////////////
		const container = this.sigmaSchema.nativeElement;
		const graph = new Graph();
		graph.addNode(1, { label: 'Node A', x: 1, y: 2, size: 20, color: '#fac0a2' });
		graph.addNode(2, { label: 'Node B', x: 2, y: 1, size: 20, color: '#7bc5ae' });
		graph.addNode(3, { label: 'Node C', x: 2, y: 3, size: 20, color: '#f38434' });
		graph.addNode(4, { label: 'Node D', x: 3, y: 2, size: 20, color: '#e22e5d' });
		graph.addNode(5, { label: 'Node E', x: 4, y: 2, size: 20, color: '#e22e5d' });
		graph.addNode(6, { label: 'Node F', x: 1, y: 3, size: 20, color: '#e22e5d' });
		graph.addNode(7, { label: 'Node G', x: 1, y: 4, size: 20, color: '#e22e5d' });
		graph.addEdge(1, 2);
		graph.addEdge(1, 3);
		graph.addEdge(2, 4);
		graph.addEdge(3, 4);
		graph.addEdge(4, 5);
		graph.addEdge(6, 4);
		graph.addEdge(6, 5);
		const renderer = new Sigma(graph, container);
		const camera = renderer.getCamera();
		const captor = renderer.getMouseCaptor();
		// State
		let draggedNode: NodeKey | null = null;
		let dragging = false;
		renderer.on('downNode', (e) => {
			dragging = true;
			draggedNode = e.node;
			camera.disable();
		});
		captor.on('mouseup', () => {
			dragging = false;
			draggedNode = null;
			camera.enable();
		});
		captor.on('mousemove', (e) => {
			if (!dragging || !draggedNode) { return; }
			// Get new position of node
			const pos = renderer.viewportToGraph(e);
			graph.setNodeAttribute(draggedNode, 'x', pos.x);
			graph.setNodeAttribute(draggedNode, 'y', pos.y);
		});
		////////////// SIGMA TEST HERE /////////////////``

Expected (wished) behavior is to have the graph keep the same scale even when I drag a node "outside" of the graph, let say 10cm on the right of  the rightmost node on the graph.
The current behavior seems to keep the whole graph displayed in the container, so when I drag a node very far, all the other ones collapse.
This sounds similar to https://github.com/jacomyal/sigma.js/issues/256 mentioned for release 1.2.1.

**Comment by sim51** [comment] 2021-08-16 13:00
Se saw some issues related to labels on the v2, and we are working on it.
You can take a look at the branches named "v2-label-grid".

**Comment by jacomyal** [comment] 2021-08-30 13:44
The latest labels grid tweaks have been pushed since `v2.0.0-beta8`, in late July, FYI. Can you please check if you still have this issue, and close it otherwise?

**Comment by knowledgeplaces** [comment] 2021-08-30 14:27
Sorry I cannot help you. Due to project constraint on delivery delay, I had to switch to another library, JSPlumb, which also better suits my needs, as I was only looking for flow diagrams.

**Comment by jacomyal** [comment] 2021-08-30 15:48
OK, thanks for this feedback :)
I'll close this issue then, since we recently pushed multiple fixes for labels appearing / disappearing randomly.

**Closed by jacomyal** 2021-08-30 15:48 UTC
Labels: v2

**Comment by tunttunen** [comment] 2024-08-06 09:13
We have this issue going on. Is there a setting to configure the randomly disappearing labels or is that a bug? The disappearance is not logical, so seems like a bug. Some nodes near each other are showing while some nodes that are not that close to any node are missing labels. Moving the node makes the label appear, but also disappear on the same areas that they were not shown to begin with.

**Comment by sim51** [comment] 2024-08-06 09:54
You can try to change these settings : 
```
// Labels
labelDensity: number;
labelGridCellSize: number;
labelRenderedSizeThreshold:number;
 ```
